export const font = {
  "Poppins-Black": require("../../assets/fonts/Poppins-Black.ttf"),
  "Poppins-Bold": require("../../assets/fonts/Poppins-Bold.ttf"),
  "Poppins-ExtraBold": require("../../assets/fonts/Poppins-ExtraBold.ttf"),
  "Poppins-ExtraLight": require("../../assets/fonts/Poppins-ExtraLight.ttf"),
  "Poppins-Light": require("../../assets/fonts/Poppins-Light.ttf"),
  "Poppins-Medium": require("../../assets/fonts/Poppins-Medium.ttf"),
  "Poppins-Regular": require("../../assets/fonts/Poppins-Regular.ttf"),
  "Poppins-SemiBold": require("../../assets/fonts/Poppins-SemiBold.ttf"),
  "Poppins-Thin": require("../../assets/fonts/Poppins-Thin.ttf"),
  "Gilroy-Black": require("../../assets/fonts/Gilroy-Black.ttf"),
  "Gilroy-Bold": require("../../assets/fonts/Gilroy-Bold.ttf"),
  "Gilroy-ExtraBold": require("../../assets/fonts/Gilroy-ExtraBold.ttf"),
  "Gilroy-Light": require("../../assets/fonts/Gilroy-Light.ttf"),
  "Gilroy-Medium": require("../../assets/fonts/Gilroy-Medium.ttf"),
  "Gilroy-Regular": require("../../assets/fonts/Gilroy-Regular.ttf"),
  "Gilroy-SemiBold": require("../../assets/fonts/Gilroy-SemiBold.ttf"),
  "Gilroy-Thin": require("../../assets/fonts/Gilroy-Thin.ttf"),
};
